[package]
edition = "2021"
name = "issue_tracker"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.5"
reqwest = {version = "0.10", features = ["blocking", "json"]}
serde_json = "1"
